server:
    port: 9001
spring:
  dubbo:
    application:
      name: service-provider2
    base-package: com.lin.service # dubbo服务发布者所在的包
    registry:
      address: 192.168.0.116 # zookeeper注册中心的地址
      port: 2181       # zookeeper注册中心的端口
      protocol: zookeeper
      register: true
    protocol:
      name: dubbo
      port: 20881
      accesslog: true
    provider:
      retries: 1
      delay: -1