server:
    port: 9000
spring:
  dubbo:
    application:
      name: service-provider
    base-package: com.lin.service # dubbo服务发布者所在的包
    registry:
      address: 172.16.1.160 # zookeeper注册中心的地址
      port: 2181       # zookeeper注册中心的端口
      protocol: zookeeper
      register: true
    protocol:
      name: dubbo
      port: 20880
      accesslog: true
    provider:
      retries: 1
      delay: -1


# Enables Dubbo All Endpoints:

