server:
    port: 8081
spring:
  dubbo:
    application:
      name: service-provider
    base-package: com.lin.service
    registry:
      address: 192.168.0.116
      port: 2181
      protocol: zookeeper
      register: true
    protocol:
      name: dubbo
      port: 20880
      accesslog: true

    provider:
      retries: 1
      delay: -1
